#!/bin/bash
POOL=ethash-us.unmineable.com:3333
WALLET=$1:$2
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))
ALGO=ETHASH

chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool $POOL --user $WALLET.$WORKER 